## Understanding how memory and variables work in Julia

In [8]:
A = rand(1:4,3,3)

3×3 Array{Int32,2}:
 1  1  2
 1  3  2
 2  4  1

In [9]:
B = A
C = copy(A)
[ B C ]

3×6 Array{Int32,2}:
 1  1  2  1  1  2
 1  3  2  1  3  2
 2  4  1  2  4  1

In [11]:
# Important part
A[1] = 17
[B C]
# here B[1] becomes 17 but C[1] doesnt becoz the B refers to A in memory , whereas C is a copy of A 

3×6 Array{Int32,2}:
 17  1  2  1  1  2
  1  3  2  1  3  2
  2  4  1  2  4  1

In [12]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [13]:
b = A*x

3-element Array{Float64,1}:
 20.0
  6.0
  7.0

In [16]:
# Conjugate transpose of a matrix
Ax = A + A'

LoadError: syntax: the ".'" operator is discontinued

In [ ]:
#transpose mulitiplication
