## Loops in Julia


### while loop

In [4]:
n = 0
print("|| ")
while n < 4
    n += 1
    print(n)
    print(" || ")
end

|| 1 || 2 || 3 || 4 || 

In [7]:
languages = ["julia","rust","golang"]

i=1
while i<=length(languages)
    println(languages[i])
    i += 1
end

julia
rust
golang


### For loop

In [16]:
for i in 1:4
    print(i," | ")
end

1 | 2 | 3 | 4 | 

#### Creating array/matrix with zeros

In [9]:
b = zeros(4,4)

4×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [11]:
for i in 1:4
    for j in 1:4
        b[i,j]= i+j
    end
end

In [12]:
b

4×4 Array{Float64,2}:
 2.0  3.0  4.0  5.0
 3.0  4.0  5.0  6.0
 4.0  5.0  6.0  7.0
 5.0  6.0  7.0  8.0

In [15]:
a = zeros(3,3)
for i in 1:3, j in 1:3
    a[i,j] = i+j
end
a

3×3 Array{Float64,2}:
 2.0  3.0  4.0
 3.0  4.0  5.0
 4.0  5.0  6.0

In [17]:
c = [i+j for i in 1:4, j in 1:4]
c

4×4 Array{Int32,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8