In [1]:
println(("Hello!" * " My word! ")^2)

Hello! My word! Hello! My word! 


In [2]:
5040 / 60

84.0

In [3]:
(((((2^2)^1)^1.3)^1.5)^1.7)^20

8.252345933335e39

In [4]:
x = 1
3*x^2-2*x+3

4

In [5]:
x = 4
(3.0 < x) && (x < 5.0)

true

In [6]:
(true || false) && false

false

In [7]:
3 & 5 > 0 

true

In [8]:
8 & 5 > 0

false

In [9]:
'a'==="a" 

false

In [10]:
x = Array{Int64}(undef,11, 12) 

11×12 Array{Int64,2}:
 -2175209547892778416  -2175206524235801328  …  -2175174363520681392
 -2175209273014871408  -2175206249357894320     -2175174088642774384
 -2175208998136964400  -2175205974479987312     -2175173813764867376
 -2175208723259057392  -2175205699602080304     -2175173538886960368
 -2175208448381150384  -2175205424724173296     -2175173264009053360
 -2175208173503243376  -2175205149846266288  …  -2175172989131146352
 -2175207898625336368  -2175204874968359280     -2175172714253239344
 -2175207623747429360  -2175204600090452272     -2175172439375332336
 -2175207348869522352  -2175204325212545264     -2175172164497425328
 -2175207073991615344  -2175204050334638256     -2175171889619518320
 -2175206799113708336  -2175203775456731248  …  -2175171614741611312

In [11]:
typeof(x)

Array{Int64,2}

In [12]:
y = -2166339512711537264
y == x[2,1]

false

In [13]:
x[2,1]

-2175209273014871408

In [14]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Array{Float64,1}:
  6.5
 -7.0

julia> inv(A) * x
2-element Array{Float64,1}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Array{Float64,1}:
 32.0
 18.0

julia> A * X == B
true
```

---

```
(\)(F::QRSparse, B::StridedVecOrMat)
```

Solve the least squares problem $\min\|Ax - b\|^2$ or the linear system of equations $Ax=b$ when `F` is the sparse QR factorization of $A$. A basic solution is returned when the problem is underdetermined.

# Examples

```jldoctest
julia> A = sparse([1,2,4], [1,1,1], [1.0,1.0,1.0], 4, 2)
4×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  1.0
  [4, 1]  =  1.0

julia> qr(A)\fill(1.0, 4)
2-element Array{Float64,1}:
 1.0
 0.0
```


In [15]:
a,b = 1,2

b = a

a = b
a

1

In [16]:
function test(input)
  println("$input"^2)
end

test(2)

22


In [17]:
function f(x)
  return 2x
  3x
  println("Hello")
end

f (generic function with 1 method)

In [18]:
f(5)

10

In [19]:
a, b = 2, 3           
function f(x)  
  b = 5 
  a*x + b
end
f(7), b

(19, 3)

In [20]:
1 + 3 < 5 && 2^2 === 4.0

false

In [21]:
x=6
(x ≥ 5.0) && (x < 7.0)

true

In [22]:
true && false && false || true

true

In [23]:
matrix = Array{Float64,2}(undef, a, b)

2×3 Array{Float64,2}:
 -2.2373e164   -6.31913e209  -2.14978e164
 -6.32124e209  -6.31973e209  -2.52888e210

In [24]:
(2^2)^3 - 2^4

48

In [25]:
2^2^3 - 2^4

240

In [26]:
println("$(6*6)")

36


In [27]:
3^2^1^5 + 3^3

36

In [28]:
(5-7)*2 +4

0

In [29]:
1 + 3 < 5 && 2^2 === 4.0

false

In [30]:
x=4
x > 0 && x <= 3

false

In [31]:
true && false && false || true

true

In [32]:
true && ((false&&false)||true)

true

In [33]:
(true&&false)&&(false||true)

false

In [34]:
((true&&false)&&false)||true

true

In [35]:
true&&(false&&(false||true))

false

In [36]:
matrix = Array{Float64,2}(undef, a, b)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [37]:
data = [1.6800483  -1.641695388; 
        0.501309281 -0.977697538; 
        1.528012113 0.52771122;
        1.70012253 1.711524991; 
        1.992493625 1.891000015;
        2.706075824 -0.463427794;
        2.994931927 -0.443566619;
        3.491852811 -1.275179133;
        3.501191722 -0.690499597;
        4.459924502 -5.516130799;
        4.936965851 -6.001703074;
        5.023289852 -8.36416901;
        5.04233698 -7.924477517;
        5.50739285 -10.77482371;
        5.568665171 -10.9171878]

15×2 Array{Float64,2}:
 1.68005    -1.6417  
 0.501309   -0.977698
 1.52801     0.527711
 1.70012     1.71152 
 1.99249     1.891   
 2.70608    -0.463428
 2.99493    -0.443567
 3.49185    -1.27518 
 3.50119    -0.6905  
 4.45992    -5.51613 
 4.93697    -6.0017  
 5.02329    -8.36417 
 5.04234    -7.92448 
 5.50739   -10.7748  
 5.56867   -10.9172  

In [38]:
data[:,1]

15-element Array{Float64,1}:
 1.6800483  
 0.501309281
 1.528012113
 1.70012253 
 1.992493625
 2.706075824
 2.994931927
 3.491852811
 3.501191722
 4.459924502
 4.936965851
 5.023289852
 5.04233698 
 5.50739285 
 5.568665171

In [39]:
data[2,:]

2-element Array{Float64,1}:
  0.501309281
 -0.977697538

In [40]:
data[1,:]

2-element Array{Float64,1}:
  1.6800483  
 -1.641695388

In [41]:
x=0
x === 0.0

false

In [42]:
mylist = [3, 2, 1]
count=1
for i in mylist
  mylist[i]=count
  count=count+1
end

mylist[3]

1

In [43]:
count=0
for i=1:3
  for j=1:3
    count=count+1
  end
end
count

9

In [44]:
summedvals = 3
for k = 1:2:5  
  summedvals = summedvals + k
end
summedvals

12